#!/bin/sh

# Check if this is a merge commit
if git rev-parse -q --verify MERGE_HEAD; then
    exit 0
fi

changed_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')
if [ -z "$changed_files" ]; then
    exit 0
fi

tox -e py38-static --
RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "Commit aborted due to failing tox checks."
    exit 1
fi

exit 0