name: 'Setup Environment'
description: 'Set up tests and extract tox environment variable'

inputs:
  python-version:
    description: 'Python version for tox environment'
    required: true

outputs:
  tox-env:
    description: 'Extracted tox environment variable'
    value: ${{ steps.extract-tox-env.outputs.tox_env }}

runs:
  using: 'composite'
  steps:

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Tox
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install tox==3.28.0

    - name: Extract tox env
      id: extract-tox-env
      shell: bash
      run: |
        tox_env_variable=$(echo "${{ inputs.python-version }}" | sed -E 's/^([0-9]+)\.([0-9]+)(\..*)?/\1\2/')
        echo "tox_env=${tox_env_variable}" >> $GITHUB_OUTPUT
