name: 'Teardown'
description: 'Handle test results and upload artifacts'

inputs:
  browser-name:
    description: 'Browser name used in tests'
    required: true
  engine:
    description: 'Tests framework'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{ inputs.browser-name }}-${{ inputs.engine }}
        path: allure-report
        retention-days: 1

    - name: Print Appium Logs on Failure
      if: ${{ inputs.engine == 'appium' }}
      shell: bash
      run: |
        echo "=== Appium Logs ==="
        cat appium.log

    - name: Check Test Results
      shell: bash
      run: |
        echo "❌ Tests failed! Please check the pytest output in the step above for details."
        exit 1
