name: Android Web Tests with Appium

on:
  push:
    branches:
      - '**'

jobs:
  android-tests:
    name: Run Appium Web Tests on Android
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          
      - name: Setup Environment
        id: setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.8'

      - name: Install Appium & UiAutomator2 Driver
        run: |
          sudo npm install -g appium@2.14.0
          appium driver install uiautomator2@3.9.0

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Set Environment Variables
        run: |
          echo "ANDROID_AVD_HOME=$HOME/.android/avd" >> $GITHUB_ENV
          echo "ANDROID_SDK_HOME=$HOME/.android" >> $GITHUB_ENV

      - name: Start Appium Server in the Background
        run: |
          nohup appium --allow-insecure chromedriver_autodownload > appium.log 2>&1 &

      - name: Install appium-doctor
        run: |
          sudo npm install -g appium-doctor

      - name: Run Appium Doctor
        run: |
          appium-doctor
          
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: reactivecircus/android-emulator-runner@v2
        name: Android Tests
        with:
          script: tox -e py38-android-web -- -k='not screenshot and not test_driver' -v
          api-level: 33
          target: google_apis
          arch: x86_64
          emulator-options: '-no-window -no-audio -no-boot-anim'
#          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
