name: Appium iOS Safari Tests

on:
  push:
    branches:
      - '**'

jobs:
  ios-tests:
    runs-on: macos-13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        id: setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.8'

      - uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install Appium & UiAutomator2 Driver
        run: |
          npm install -g npm@10.9.0
          npm install -g appium@2.14.0
          appium driver install uiautomator2@3.9.0
#          npm install -g appium-doctor  # Uncomment for debug
#          appium-doctor  # Uncomment for debug

      - name: Start Appium Server in the Background
        run: |
          nohup appium > appium.log 2>&1 &

      - uses: futureware-tech/simulator-action@v4
        name: iOS Simulator
        with:
#          udid: '116D1E30-F4F0-4737-BFDB-746F38A77AF8'
          os: 'iOS'
          model: 'iPhone 15'
#          os_version: '17.2'
          wait_for_boot: true

      - name: Run Appium Safari tests
        id: tests
        run: |
          tox -e py38-ios-web -- -v --alluredir=allure-report -k test_wait_element_text1
        continue-on-error: true

      - name: Teardown (Allure Report and Error Handling)
        if: ${{ steps.tests.outcome == 'failure' }}
        uses: ./.github/actions/teardown
        with:
          browser-name: "chrome"
          tox-env: "38"
          engine: "appium"
