name: Android Web Tests with Appium

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    name: Run Appium Web Tests on Android
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723
        options: >-
          --health-cmd "curl -s http://localhost:4723/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Install Android Dependencies
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "emulator" "system-images;android-34;google_apis;x86_64"
          avdmanager create avd -n testAVD -k "system-images;android-34;google_apis;x86_64" --device "pixel_4"

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd testAVD -no-window -no-audio -gpu off &
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'

      - name: Install Appium Client Dependencies
        run: |
          pip install -r requirements.txt  # Ensure your Python test dependencies are listed here

      - name: Run Tests
        run: |
          pytest tests/  # Adjust this path to your test folder
