name: Update Screenshot References

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit sha for artifacts lookup'
        required: true

jobs:
  screenshots_updating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow==9.4.0 requests==2.32.3

      - name: Run script
        run: |
          python tests/adata/pull_ci_artifacts.py ${{ github.event.inputs.commit_sha }} -t ${{ secrets.PAT }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Screenshots updated for ${{ github.event.inputs.commit_sha }}" || echo "No changes to commit"
          
      - name: Set up Git for authentication
        run: |
          git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Push changes
        run: |
          git push origin ${{ github.ref }}
