name: Selenium Selenoid Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  selenium-selenoid-chrome:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: selenoid/vnc:chrome_112.0
        options: --privileged --memory=4g
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.28.0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Selenium tests
        run: |
          tox -e py38-selenium-chrome -- --env remote --headless -v --alluredir=allure-results -k test_screenshot_remove || true
          
      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean
          
      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1

      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main' && success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
