name: Selenium Safari Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  selenium-safari:
    runs-on: macos-13

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.12" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Setup tests
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.28.0
          
      - name: Extract tox env
        run: |
          tox_env_variable=$(echo "${{ matrix.python-version }}" | sed 's/\.//g')
          echo "TOX_ENV=${tox_env_variable}" >> $GITHUB_ENV

      - name: Enable Safari Remote Automation
        run: |
          safaridriver --version
          sudo safaridriver --enable

      - name: Run Selenium Safari tests with py${{ matrix.python-version }}
        id: tests
        run: |
          tox -e py${{ env.TOX_ENV }}-selenium-safari -- -v --alluredir=allure-report --reruns=2
        continue-on-error: true
          
      - name: Upload Allure Report as Artifact
        if: steps.tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-safari-selenium-${{ env.TOX_ENV }}
          path: allure-report
          retention-days: 1

      - name: Check Test Results
        if: steps.tests.outcome == 'failure'
        run: |
          echo "❌ Tests failed! Check the Allure Report for details."
          exit 1 

