name: Selenium Selenoid Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  selenium-selenoid-chrome:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: selenoid/vnc:chrome_112.0
        options: --privileged --memory=4g
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup tests
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.28.0
          mkdir -p allure-report
          chmod -R 777 allure-report
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Run Selenium tests
        id: tests
        run: |
          tox -e py38-selenium-chrome -- --env remote --headless -v --sv
