name: Setup Tox

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tests
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.28.0

      - name: Extract tox env
        run: |
          tox_env_variable=$(echo "${{ inputs.python-version }}" | sed -E 's/^([0-9]+)\.([0-9]+)(\..*)?/\1\2/')
          echo "TOX_ENV=${tox_env_variable}" >> $GITHUB_ENV
