name: Static Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  static:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        id: setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Static tests with ${{ matrix.python-version }}
        run: |
          tox -e py${{ steps.setup.outputs.tox-env }}-static
