name: Run Static Tests

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  pull_request:
    branches:
      - '**'  # Trigger on pull request to any branch

jobs:
  test:
    runs-on: ubuntu-latest  #'windows-latest' / 'macos-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Tox and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.2.8 

      - name: Run Tox
        run: |
          tox -e py38-static
